-- Retrieved from: https://gist.github.com/Stuyk/c65f345b73a7eab4a0ee30b540e57c76
HairOverlaysMale = {
    { collection = 'mpbeach_overlays',     overlay = 'FM_Hair_Fuzz' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_004' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_005' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_006' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_007' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_008' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_009' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_013' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_011' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_012' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
    { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGInd_M_Hair_000' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_000' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_001' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_002' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_003' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_004' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_005' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_006' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_000_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_001_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_002_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_003_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_004_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_005_M' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_004' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_005' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_006' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_007' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_008' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_009' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_013' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_011' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_012' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
    { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
    { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_000' },
    { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
    { collection = 'multiplayer_overlays', overlay = 'NGInd_M_Hair_000' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_000' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_001' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_002' },
    { collection = 'mplowrider_overlays',  overlay = 'LR_M_Hair_003' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_004' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_005' },
    { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_006' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_000_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_001_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_002_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_003_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_004_M' },
    { collection = 'mpbiker_overlays',     overlay = 'MP_Biker_Hair_005_M' },
    {
        collection = 'mpgunrunning_overlays',
        overlay = 'MP_Gunrunning_Hair_M_000_M'
    },
    {
        collection = 'mpgunrunning_overlays',
        overlay = 'MP_Gunrunning_Hair_M_001_M'
    }
};
